### PR TITLE
43 issue on page docsapplicationsnotebooksportfolio optimizationhtml

### PR DESCRIPTION
**Pull request by tschm**

### CODE REVIEW

**Comment by tschm** [comment]
@phschiele 
There is an issue with the solver. Can you please have a look as you created this notebook?

**Review by phschiele — APPROVED** [review]
@tschm With your changes I get
```
Factor model solve time = 0.045474021
Single model solve time = 3.570194763
```
which should suffice to make the point that the factor model is much faster.

With
```py
n = 3000
m = 30
```
It already takes up a considerable amount of memory and many minutes to solve.

-> I suggest keeping your changes to make sure it runs everywhere and we still do not lose the argument we want to make. With those changes in place, running the full notebook only takes a few seconds to run, so we could include it in the book.

**Comment by tschm** [comment]
Well, I guess the results reflect the factor 100 :-) I will adjust the text in notebook

**Comment by tschm** [comment]
@phschiele please compare the number of iterations for factor vs full example... Massive differences

**Review by PTNobel — APPROVED** [review]

**Pull request merged**
